---
- hosts: all
  remote_user: root
  become: yes
  vars:
    jenkins_hostname: cd
    jenkins_http_port: 8088
    solita_jenkins_security_realm: none
    solita_jenkins_plugins:
      - maven-plugin
      - git
      - ansible
      # Optional
      - ansicolor
  roles:
    - solita.jenkins
    - deployment_playbook