- name: Ensure Git are installed
  yum: name={{item}} state=present
  with_items:
   - git-all
   - epel-release

- name: Ensure Ansible (EPEL required) is installed
  yum: name={{item}} state=present
  with_items:
   - ansible

- name: Ensure a directory to store deployment playbook
  file:
    path: "/ansible"
    state: directory
    mode: 0744
    owner: jenkins
    group: jenkins

- name: Ensure Ansible playbook and related config stuff is present
  copy:
    src: "../../ansible/"
    dest: "/ansible/"
    mode: 0744
    owner: jenkins
    group: jenkins

- name: Ensure the existence of a directory to store Vagrant private key
  file:
    path: "/vagrant"
    state: directory
    mode: 0744
    owner: jenkins
    group: jenkins

- name: Vagrant private key is present
  copy:
    src: "vms_private_key"
    dest: "/vagrant/vms_private_key"
    mode: 0700
    owner: jenkins
    group: jenkins