---
- name: Install Java 1.8 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - java-1.8.0-openjdk

- name: Ensure app dir exists
  file: path=/usr/share/vertx_app/ recurse=yes state=directory

- name: Copy the Vert.x application jar package
  copy: src={{ app_jar }} dest=/usr/share/vertx_app/{{ app_jar }} mode=0755

- name: ls command on Vert.x app folder
  command: ls -l /usr/share/vertx_app/

- name: Download and extract Vert.x core
  unarchive: copy=no src=https://bintray.com/artifact/download/vertx/downloads/vert.x-3.2.1-full.zip dest=/usr/share creates=/usr/share/vertx

- name: Run Vert.x application
  command: vertx run {{ app_class }} -cp /usr/share/vertx_app/{{ app_jar }}
