---
- hosts: all
  tasks:
    - command: echo "$PATH"
      register: default_path
    - command: echo "$WORKSPACE"
      register: jenkins_job_workspace

- hosts: all
  remote_user: vagrant
  become: yes
  environment:
    JAVA_HOME: /usr/lib/jvm/jre-1.8.0-openjdk/
    PATH: "{{ default_path.stdout }}"
  roles:
    - vertx-standalone