---
- hosts: audit-service
  remote_user: vagrant
  become: yes
  roles:
    - db-setup

- hosts: all
  remote_user: vagrant
  become: yes
  environment:
    JAVA_HOME: /usr/lib/jvm/jre-1.8.0-openjdk/
  roles:
    - { role: vertx-app-deployment, jenkins_job_workspace: "{{ lookup('env', 'WORKSPACE') }}" }